.github/workflows/build-wheels.yml
.github/workflows/code-quality.yml
docker/python-3.10.dockerfile
docker/python-3.11.dockerfile
docker/python-3.9.dockerfile

Port of https://github.com/aleph-im/aleph-client/pull/149

Fix: GitHub actions failed on Ubuntu due to Grub

---

.coveragerc
examples/httpgateway.py
examples/metrics.py
examples/mqtt.py
examples/store.py
setup.cfg
setup.py
src/aleph/sdk/__init__.py
src/aleph/sdk/client.py
tests/integration/itest_aggregates.py
tests/integration/itest_forget.py
tests/integration/itest_posts.py
tests/unit/test_asynchronous.py
tests/unit/test_asynchronous_get.py
tests/unit/test_synchronous_get.py

Renames `aleph_client` into `aleph.sdk` and `(Authenticated)UserSession` into `(Authenticated)AlephClient`.
Do not squash.

Rename project and UserSession

---

src/aleph/sdk/client.py
tests/unit/test_asynchronous.py

To allow programmatic deployment of VMs with metadata

Add metadata parameter to create_program()

---

.github/workflows/pytest-docker.yml
docker/python-3.11.dockerfile
setup.cfg

Problem: some dependencies only support Python 3.11 in the latest releases. We do not want to restrict the version range for users of older Python versions.
Solution: specify loose versions for Python<3.11 and the correct ones for Python 3.11.

Fix: support for Python 3.11

---

src/aleph/sdk/chains/common.py
src/aleph/sdk/chains/cosmos.py
src/aleph/sdk/chains/ethereum.py
src/aleph/sdk/chains/nuls1.py
src/aleph/sdk/chains/nuls2.py
src/aleph/sdk/chains/sol.py
src/aleph/sdk/chains/substrate.py
src/aleph/sdk/chains/tezos.py
src/aleph/sdk/exceptions.py
tests/unit/test_chain_ethereum.py
tests/unit/test_chain_solana.py
tests/unit/test_chain_tezos.py

Problem: Users cannot verify signatures
Solution: Implement verify_signature() functions for **Ethereum** and **Solana** signatures, more are following.
Partly solves: #9

Feature: Signature verification for Solana and Ethereum messages

---

src/aleph/sdk/vm/app.py

Problem: @app.on_event("startup") would not be triggered on uvicorn startup
Solution: Relay "lifespan" events from the AlephApp to the http_app

Fix: Relay startup event through AlephApp

---

setup.cfg
src/aleph/sdk/chains/nuls1.py
src/aleph/sdk/conf.py
src/aleph/sdk/types.py

- Update: aleph-message to 0.3.2
- Fix: __all__ did not export GenericMessage
- Fix: mypy raised an error due to Optional[pub_key]
- Fix: Remove non relevant settings

Minor fixes

---

src/aleph/sdk/chains/ethereum.py
tests/unit/test_chain_ethereum.py
tests/unit/test_chain_solana.py

Problem: As Ethereum addresses may contain checksum information in capitalizing their letters, comparing the input address and the resulting public_key of the signature verification process resulted in false negatives.
Solution: Casefold both the address and public key before comparing them. Added further tests to both ETH and SOL accounts to increase coverage and test for other unforeseen errors.

Fix: ETH verify_signature fails on checksummed addresses

---

src/aleph/sdk/chains/common.py

Problem: The symlink can exist, but it can be dead. For example, unit tests may remove the file but not the symlink.
Solution: We add a check to determine if it is a symlink and if it is dead. In this case, we unlink it.

Fix: SDK error when retrieving fallback private key, but the symlink was dead.

---

src/aleph/sdk/vm/cache.py

Problem: the user can only specify the URL of the cache or a complete aiohttp client session object.
Solution: mirror what is done for the `AlephClient` class and allow a `unix_socket` parameter in the constructor of `VmCache` to build the client session correctly for the user.

Feature: VM cache did not support connecting through a Unix socket

---

setup.cfg
src/aleph/sdk/chains/common.py

Problem: aiomqtt has been taken over by a completely different team and the new version (1.0.0) is completely incompatible with our current example.
Solution: use the latest version of the old project.

Fix: CI was broken because of aiomqtt update

---

src/aleph/sdk/chains/common.py
src/aleph/sdk/utils.py
tests/unit/test_chains.py
tests/unit/test_utils.py

The signature buffer is affected by the new formatting of string
enums.
Solution: use the value of the message type enum.
Co-authored-by: Olivier Desenfans <desenfans.olivier@gmail.com>

Problem: Signatures generated with Python 3.11 are invalid

---

src/aleph/sdk/client.py
src/aleph/sdk/exceptions.py
src/aleph/sdk/utils.py
src/aleph/sdk/vm/cache.py
tests/unit/test_download.py

Solutions:
- Add a function called download_file_ipfs that downloads from ipfs.io/ipfs/.
- Refactor the current download process to include:
- Chunk size and storage into a buffer (BytesIO). (memory friendly)
- Add a test for the download functionality.

Feature: download on ipfs client

---

src/aleph/sdk/client.py
src/aleph/sdk/utils.py
tests/unit/test_chain_ethereum.py
tests/unit/test_chain_nuls1.py
tests/unit/test_chain_solana.py
tests/unit/test_download.py

Because of updates in rules enforced by flake8, previously good code now failed the code quality workflow.

fix formatting, flake8 bugs and imports

---

setup.cfg
src/aleph/sdk/conf.py
src/aleph/sdk/domain.py
src/aleph/sdk/exceptions.py
tests/unit/test_domains.py

Implement AlephDNS from @aliel inside SDK

Feature : AlephDNS

---

src/aleph/sdk/wallets/ledger/ethereum.py

Fix: Invalid handling of optional value

---

src/aleph/sdk/vm/app.py
tests/unit/test_vm_app.py

This simple property returns the `item_hash` of the Aleph message that created the VM that is currently running (and invoking the method).

Add AlephApp.vm_hash

---

src/aleph/sdk/client.py

Client-side deprecation of `message_type`, see: https://github.com/aleph-im/pyaleph/pull/444

Allow multiple message types

---

setup.cfg
src/aleph/sdk/chains/common.py
src/aleph/sdk/chains/cosmos.py
src/aleph/sdk/chains/ethereum.py
src/aleph/sdk/chains/nuls1.py
src/aleph/sdk/chains/nuls2.py
src/aleph/sdk/chains/remote.py
src/aleph/sdk/chains/sol.py
src/aleph/sdk/chains/substrate.py
src/aleph/sdk/chains/tezos.py
src/aleph/sdk/conf.py
src/aleph/sdk/wallets/ledger/ethereum.py
tests/unit/conftest.py
tests/unit/messages.json
tests/unit/test_chain_ethereum.py
tests/unit/test_chain_solana.py
tests/unit/test_chain_substrate.py
tests/unit/test_chain_tezos.py

`BaseAccount.sign_raw()` accepts raw bytes and outputs a signature as a string in the preferred encoding.
This allows signing of arbitrary data besides Aleph messages, making it a useful tool in dApp development.

Add sign_raw()

---

src/aleph/sdk/client.py

Problem: a user reports that publishing a message falls because of a 405 error returned from `POST /messages`. The fallback only takes 404 into account, but a 405 is actually more likely because `GET /messages` exists.
Solution: accept both 404 and 405 as a sign that the node does not support `POST /messages`.

Fix: support 405 from POST /messages in broadcast fallback

---

src/aleph/sdk/client.py

Problem: using `create_post()` with an object containing datetime, UUIDs and other types not serializable by the Python `json` module fails.
Solution: as we already use Pydantic all over the place, use the Pydantic encoder as default for all the types not serializable by the `json` module.

Fix: allow user to specify datetime and UUID objects in post content

---

src/aleph/sdk/conf.py

A program could not run `pip freeze` with so little memory.
Solution: Bump the default memory to 256 MB.

Fix: 128 MB of RAM was too small

---

src/aleph/sdk/conf.py

We released a new runtime based on Debian 12.
This changes the default configuration to use the new runtime.

Fix: Default runtime was obsolete

---

setup.cfg

Problem: `pip install .[testing]` is not enough to run all tests successfully.
Solution: add missing packages to the "testing" install target.

Fix: add ledgereth to "testing" install target

---

tests/unit/test_asynchronous.py
tests/unit/test_upload.py

Title says it all. CI breaking was due to #69, which had not executed all workflows.

Hotfix: Formatting and mypy issues were not tested in PR workflow

---

.github/workflows/build-wheels.yml
README.md
tests/unit/test_upload.py

The workflow is failing sometime during this test due to `ServerDisconnectErrors`.
We can Mocked `AuthenticatedAlephHttpClient` to remove server call

Fix: Upload Test wasn't mocked

---

src/aleph/sdk/client/abstract.py
src/aleph/sdk/client/authenticated_http.py

Add allow_amend, internet and aleph_api parameters to create_program

---

src/aleph/sdk/client/abstract.py
src/aleph/sdk/client/authenticated_http.py
tests/unit/test_asynchronous.py

Introduce `create_instance()` with slight modifications from https://github.com/aleph-im/aleph-client/pull/156

Add `create_instance` method

---

setup.cfg
src/aleph/sdk/conf.py
src/aleph/sdk/domain.py
src/aleph/sdk/exceptions.py
tests/unit/test_domains.py

The previous Pull Request #47 failed to match our standards, broke PEP8 and code quality and caused issues for further development.
This is a new Pull Request aiming at getting these changes merged.
* Feature : AlephDNS add instances support
add ipfs support
add program support
---------

Feature : AlephDNS (2nd attempt)

---

src/aleph/sdk/client/abstract.py
src/aleph/sdk/client/http.py
src/aleph/sdk/exceptions.py
tests/unit/conftest.py
tests/unit/post.json
tests/unit/test_asynchronous.py
tests/unit/test_asynchronous_get.py

Inspired by https://github.com/aleph-im/aleph-client/pull/129/files:
- `get_message` now requires less parameters and raises `ForgottenMessageError` if message existed, but was forgotten
- Uses the `/api/v0/messages/{item_hash}` endpoint to do so -> should potentially lead to performance improvements
- The tests in `test_asynchronous_get.py` are now fully mocked
- Refactored fixtures from `test_asynchronous_get.py` and `test_asynchronous.py` to be included in `conftest.py`

Refactor: Simplify and improve `get_messages`; use mocked responses

---

src/aleph/sdk/client/authenticated_http.py
tests/unit/test_asynchronous.py

Supersedes https://github.com/aleph-im/aleph-client/pull/131

Add extended JSON encoder for datetime objects in message encoding

---

.github/workflows/pr-rating.yml
src/aleph/sdk/client/abstract.py
src/aleph/sdk/client/authenticated_http.py
src/aleph/sdk/client/http.py
src/aleph/sdk/exceptions.py
tests/unit/conftest.py
tests/unit/rejected_message.json
tests/unit/test_asynchronous.py
tests/unit/test_asynchronous_get.py

- Refactor `submit()` and `broadcast()` methods to add `raise_on_rejected` parameter. This allows client methods to implement their own exception handling on broadcast.
- Implement `InsufficientFundsError` if creating an instance failed due to low funds.

Refactor: Add `InsufficientFundsError` in `create_instance`

---

src/aleph/sdk/client/authenticated_http.py

Fix issue with optional argument in the constructor of AuthenticatedHTTP client.

Fix: `api_server` is now actually optional

---

examples/httpgateway.py
examples/metrics.py
examples/mqtt.py
setup.cfg
src/aleph/sdk/chains/nuls1.py
src/aleph/sdk/chains/remote.py
src/aleph/sdk/client/authenticated_http.py
src/aleph/sdk/conf.py
src/aleph/sdk/types.py
src/aleph/sdk/utils.py
tests/unit/conftest.py
tests/unit/test_chain_nuls1_compat.py

Problem: new version of black invalidates prior formatting
Solution: update black and reformat files

[Lint] Reformat with latest `black` version

---

src/aleph/sdk/client/authenticated_http.py
src/aleph/sdk/client/http.py

I had the following problem:
```ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate```
when using the function: **AuthenticatedAlephHttpClient** and **AlephHttpClient**
I searched on the internet for a way to solve this problem, but all the commands/advice given didn't work.
So I thought it would be a good idea to give the user the option of specifying a specific SSL certificate if they wish.
This worked in my case and gave me the option of continuing to use the SDK provided by Aleph.

Feature: Choose a ssl certificate other than the default one

---

src/aleph/sdk/chains/ethereum.py
tests/unit/test_chain_ethereum.py

Users could not easily import or migrate accounts using their mnemonic representation.
Solution: Add a static method `from_mnemonic` on the `ETHAccount` class.
Discussion: This is a first step and this behaviour can be extended to more chains in the future.

Fix: An ETH account could not be initialized from its mnemonic

---

src/aleph/sdk/client/abstract.py
src/aleph/sdk/client/authenticated_http.py

Problem: Instances don't use program encodings. This argument was left from refactoring.
Solution: Drop the argument.

Fix: `create_instance` required a program `encoding`

---

setup.cfg
src/aleph/sdk/__init__.py
src/aleph/sdk/client/abstract.py
tests/unit/test_init.py

Update Aleph SDK client to raise ImportError with appropriate error message for deprecated classes and types.

[Feature] Deprecation messages for invalid imports

---

setup.cfg
src/aleph/sdk/__init__.py
src/aleph/sdk/client/abstract.py
tests/unit/test_init.py

Deprecation messages are displayed when either trying to use the now abstract classes `AlephClient` and `AuthenticatedAlephClient` in the form of either
- `ImportError` when imported directly from `aleph.sdk`
- or `NotImplementedError` when imported from their source files, with additional info about which classes to use instead.

Feature: Add Deprecation Message

---

src/aleph/sdk/chains/common.py
src/aleph/sdk/query/filters.py
src/aleph/sdk/utils.py

- Missing sort_by/sort_order filters: [issue 95 on SDK](https://github.com/aleph-im/aleph-sdk-python/issues/95)
- message_types passed as arg to MessageFilter breaks if nb elements > 1
- Modified MessageFilter/PostFilter + Added SortBy/SortOrder enums
- Fix typo on msgType -> msgTypes
- Also requires merging of [PR](https://github.com/aleph-im/pyaleph/pull/555) on PyAleph repo
@hoh

Fix msgTypes + Add sort_by/sort_order args to MessageFilter/PostFilter

---

setup.cfg

Problem: Too strict of a eth-abi==4.0.0b2 dependency makes it difficult to install the latest version of the SDK on aleph-nodestatus.

Loosen eth-abi dependency

---

src/aleph/sdk/client/abstract.py
src/aleph/sdk/client/authenticated_http.py
tests/unit/test_asynchronous.py

Problem: Using the `create_instance` method need to have the `rootfs_name` field filled, that finally is ignored on the final message.
Solution: Removed `rootfs_name` instance creation field.

Removed `rootfs_name` instance creation field

---

setup.cfg
src/aleph/sdk/chains/common.py

`eciespy` is not actively maintained anymore and may cause problems when installed alongside newer versions of web3py and ethereum-related packages.
The solution makes installing eciespy optional, deprecates the `Account.encrypt()` and `.decrypt()` functions and will move them in future to their own `aleph.sdk.encryption` module.

Deprecate encryption methods and make eciespy dependency optional

---

.github/workflows/build-wheels.yml
README.md
pyproject.toml

Still tried to hash now-nonexistant `setup.cfg` and `setup.py` files to determine hash to lookup cached dependencies.
This causes the latest CI/CD flow on main to fail.

Fix Hashing for Caching Dependencies in Build Wheel GH Action

---

.github/workflows/pytest.yml

Problem: Since the SDK is a library, it should not enforce the
version of the libraries it requires too strictly.
This causes issues when an incompatible dependency upgrade
breaks compatibility without anyone noticing except for the next
CI build.
Solution: Run tests daily with the latest dependencies.

Fix: No notification when dependency update breaks

---

src/aleph/sdk/client/abstract.py
src/aleph/sdk/client/authenticated_http.py
src/aleph/sdk/utils.py

Problem: Developers could not generate signed messages without using the AlephHttpClient.
Solution: Move and rename the method on the abstract class; Move the utility that generates sha256 hashes to utils.py.

Fix: Could not generate signed messages outside HTTP client

---

tests/unit/test_asynchronous.py

AttributeError: 'called_once' is not a valid assertion. Use a spec for the mock if 'called_once' is meant to be an attribute.

Fix: 'called_once' is not a valid assertion.

---

src/aleph/sdk/__init__.py

Solution: Use `importlib.metadata.version` instead.

Fix: pkg_resources is obsolete to get package version

---

pyproject.toml
tests/unit/conftest.py
tests/unit/test_domains.py
tests/unit/test_download.py
tests/unit/test_wallet_ethereum.py

Solution: Add ruff to check the code quality and fix the reported errors.

Fix: Ruff did not check code quality

---

src/aleph/sdk/client/abstract.py
src/aleph/sdk/client/authenticated_http.py
src/aleph/sdk/types.py

- **Fix: Typing of item hashes were `str` not ItemHash**
- **Fix: Typing: Protocol AccountFromPrivateKey lacked method `sign_raw`**

Fix type hints 

---

.github/workflows/pytest.yml

When "using bundled libsecp256k1", the setup using `/tmp/venv/bin/hatch run testing:test` fails to proceed on Python 3.12.
That library `secp256k1` has been unmaintained for more than 2 years now (0.14.0, Nov 6, 2021), and seems to not support Python 3.12.
The error in the logs:
```
File "/tmp/pip-build-env-ye8d6ort/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 862, in get_command_obj
cmd_obj = self.command_obj[command] = klass(self)
^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
[end of output]
```
See failing CI run:
https://github.com/aleph-im/aleph-sdk-python/actions/runs/9613634583/job/26516767722

Fix: Pythom 3.12 fails setup libsecp256k1

---

src/aleph/sdk/client/abstract.py
src/aleph/sdk/client/authenticated_http.py
tests/unit/test_asynchronous.py

Problem: As a user we cannot create a confidential VM using the SDK.
Solution: Implement new confidential VM fields.

Add new Confidential fields

---

src/aleph/sdk/client/http.py
tests/unit/conftest.py

This should fix the CI, it used to be a deprecated warning before but this is now an error.
Idk if this changes the way you are supposed to use this class and if it could break the existing API :/

fix: aiohttp.ClientSession needs to be created inside an async function

---

src/aleph/sdk/client/authenticated_http.py
src/aleph/sdk/client/http.py

Fix 146: Autenticated client was overriding the manager and it was causing issue

---

pyproject.toml
src/aleph/sdk/client/abstract.py
src/aleph/sdk/client/http.py
src/aleph/sdk/exceptions.py
src/aleph/sdk/query/responses.py
tests/unit/conftest.py
tests/unit/test_price.py

Problem:
In the Pay-As-You-Go (PAYG) flow, we need to retrieve the price of a program.
Solution:
Implement the get_program_price function to query the `/api/v0/price/` endpoint and fetch the price of the program.

Feature: get_program_price

---

pyproject.toml
src/aleph/sdk/chains/ethereum.py
src/aleph/sdk/conf.py
src/aleph/sdk/connectors/superfluid.py
tests/unit/test_superfluid.py

This PR integrates superfluid.py with aleph-sdk-python by using the ETHAccount class. It eliminates the need to directly use private_key_str, making transactions more secure and easier to manage.:
```
create_flow_operation = cfaV1Instance.create_flow(
sender, receiver, super_token, flow_rate)
transaction_hash = create_flow_operation.exec(PRIVATE_KEY
```
exemple of usage :
```python
my_acc = ETHAccount(
private_key,
chain=Chain.AVAX,
rpc=settings.AVAX_RPC,
chain_id=settings.AVAX_CHAIN_ID,
)
transaction_hash = my_acc.create_flow(receiver, Decimal(0.03))
```
This PR also introduce:
-update_flow
-delete_flow
-get_flow

Feature: Superfluid integrations

---

pyproject.toml
src/aleph/sdk/chains/ethereum.py
src/aleph/sdk/conf.py
src/aleph/sdk/connectors/superfluid.py
src/aleph/sdk/evm_utils.py
src/aleph/sdk/types.py
tests/unit/test_superfluid.py

- Add web3py depdendencies
- Methods for balances (eth & aleph) and transactions
- Superfluid connector rework
- New config for EVM chains (allowing easy addition of new chains in the future)

Upgrade to web3py, fixes on ETHAccount/PAYG, EVM configs

---

pyproject.toml

Fix: Reload the official superfluid dependency.
Fix: Disable completely the support for Python 3.8

Reload the official superfluid dependency.

---

src/aleph/sdk/account.py

Fix _load_account when both string & path private key are provided

---

src/aleph/sdk/client/vm_confidential_client.py
tests/unit/test_vm_confidential_client.py

Fix right type on create_session

---

src/aleph/sdk/client/http.py

Problem: Currently, there is no method to retrieve the status of a message using its item_hash. This limitation makes it difficult to efficiently check the processing state of specific messages.
Solution: I have added a new method, get_message_status, which allows users to obtain the status of a message by providing the item_hash. I have updated the get_message method to optionally return the status of a message when requested, improving overall flexibility and functionality.

Feature: get_message_status and overload of get_message to return status

---

pyproject.toml

feat: add pyproject-fmt

---

src/aleph/sdk/account.py

Wrong account config alert where shown loading the default account:
This PR fixes that wrong warning message.

Fix wrong account config alert

---

src/aleph/sdk/account.py

When loading a solana account, it was always falling back to ETHAccount.

Fix wrong chain account loading

---

pyproject.toml

Problem: If a user wants to deploy a VM using the GPU support, he cannot do it from the SDK because it's not updated with latest aleph_message protocol.
Solution: Update aleph_message protocol with last changes.

Implement GPU support

---

src/aleph/sdk/client/vm_client.py

Variation on perform_operation that allow a raw response. Move from the aleph-client code introduced in https://github.com/aleph-im/aleph-client/pull/304

Add VmClient.operate

---

src/aleph/sdk/client/abstract.py

Fixed to match the value of `settings.DEFAULT_INSTANCE_MEMORY` that is used in the code.

fix(create_instance): Default memory in docstring

---

src/aleph/sdk/client/http.py
src/aleph/sdk/conf.py
src/aleph/sdk/types.py
src/aleph/sdk/utils.py

Required for https://github.com/aleph-im/aleph-client/pull/311

Fix for Terms & Conditions

---

.github/workflows/build-wheels.yml
.github/workflows/pytest.yml
pyproject.toml
tests/unit/test_chain_tezos.py

feat: upgrade to our latest version of pytezos

---

src/aleph/sdk/chains/ethereum.py
src/aleph/sdk/chains/evm.py
src/aleph/sdk/client/abstract.py
src/aleph/sdk/client/authenticated_http.py
src/aleph/sdk/client/http.py
src/aleph/sdk/conf.py
src/aleph/sdk/connectors/superfluid.py
src/aleph/sdk/evm_utils.py
src/aleph/sdk/exceptions.py
src/aleph/sdk/types.py
src/aleph/sdk/utils.py
tests/unit/aleph_vm_authentication.py
tests/unit/test_asynchronous.py
tests/unit/test_price.py
tests/unit/test_superfluid.py
tests/unit/test_utils.py

Jira: [ALEPH-393](https://aleph-im.atlassian.net/browse/ALEPH-393), [ALEPH-397](https://aleph-im.atlassian.net/browse/ALEPH-397), [ALEPH-400](https://aleph-im.atlassian.net/browse/ALEPH-400)
Needed for this [PR on SDK](https://github.com/aleph-im/aleph-client/pull/332)
- Move/improve flow code parts from CLI to SDK
- Add utils functions
- Add `make_instance_content` and `make_program_content`
- Refactor `create_instance` and `create_program`
- Add `get_estimated_price`
- Fixes for mypy/ruff/pytest
- Minor improvements
- Remove firecracker rootfs hashes for instances

Changes for new pricing system

---

tests/integration/config.py

Server api1.aleph.im is very slow and outdated
(Core i7 from 2018, up to 40 seconds to respond
to `/metrics` in the monitoring).
We suspect that this causes issues in the
monitoring and performance of the network.
This branch removes all references to api1 and
replaces them with api3 where relevant.

Fix: Remove references to slow server api1.aleph.im

---

src/aleph/sdk/account.py
src/aleph/sdk/chains/svm.py
tests/unit/test_chain_svm.py

This PR adds:
1) SVMAccount based on SOLAccount (As EVMAccount we default chain onthe message to SOL for now)
2) New SVM Chain in chain_account_map to be able to load SVM wallet
3) New test for SVMAccount

Feature: New SVMAccount

---

pyproject.toml
src/aleph/sdk/chains/ethereum.py
src/aleph/sdk/evm_utils.py

Feature: Update `web3` dependency

Update `web3` dependency

---

src/aleph/sdk/conf.py

Without the fix, any variable present in a `.env` file where the SDK is used (including the CLI, and products using the CLI, like the [Web3 Hosting GitHub Action](https://github.com/marketplace/actions/aleph-web3-hosting)) throws an error that make it completely unusable:
With the fix, it ignores those variables:
This is due to Pydantic v2 being more strict when unexpected fields are given, we have to explicitly ignore them.

fix: Pydantic v2 errors on unknown env vars

---

src/aleph/sdk/client/http.py

feat: use new endpoint to get message status

---

src/aleph/sdk/client/http.py
src/aleph/sdk/client/services/crn.py
src/aleph/sdk/client/services/pricing.py
src/aleph/sdk/client/services/scheduler.py
src/aleph/sdk/types.py
src/aleph/sdk/utils.py
tests/unit/services/pricing_aggregate.json
tests/unit/services/test_pricing.py

This Pr adds a new `Pricing` Services to allow user to fetch price of services direcly from SDK.
Related ClickUp, GitHub or Jira tickets : ALEPH-541
This pull request introduces a new `Pricing` service to the SDK, enabling programmatic access to pricing information for various Aleph services. It also adds GPU information helpers to the CRN service, utility functions for compute unit calculation, and comprehensive unit tests for the pricing logic. The changes are grouped as follows:
**New Pricing Service:**
* Added a new `Pricing` service (`src/aleph/sdk/client/services/pricing.py`) with models for pricing entities, groups, and methods to fetch and filter pricing information for different Aleph services. This includes support for GPU, confidential, and persistent program pricing.
* …

Feature: Pricing Services

---

src/aleph/sdk/client/http.py
src/aleph/sdk/client/services/instance.py
src/aleph/sdk/client/services/pricing.py
src/aleph/sdk/query/filters.py
src/aleph/sdk/query/responses.py
src/aleph/sdk/types.py
tests/unit/services/pricing_aggregate.json
tests/unit/test_balance.py
tests/unit/test_credits.py

This Pr adds add : 
- Credits field on Price to handle credits on pricing aggregate
- New method on `AlephHttpClient` : `get_credit_balance` and `get_credits`
Related ClickUp, GitHub or Jira tickets : ALEPH-620
This pull request adds comprehensive support for querying and handling credit balances in the Aleph SDK. It introduces new API methods to retrieve credit balances for individual addresses and for all addresses, adds corresponding filter and response classes, and updates the pricing schema to include credit-based pricing. Additionally, new unit tests ensure the correctness of these features.
**Credit balance API and query support:**
* Added `get_credit_balance` and `get_credits` async methods to `AlephHttpClient` for fetching credit balances for a specific address and for all …

Feature: credits system

---

src/aleph/sdk/client/http.py
src/aleph/sdk/client/services/crn.py
src/aleph/sdk/query/responses.py
src/aleph/sdk/types.py
tests/unit/test_price.py

fix: https://github.com/aleph-im/aleph-sdk-python/pull/236
and fix an issue where crn wouldn't get fetch on the crn list due to filter
Also include the fix from this other PR spotted by @RezaRahemtola (https://github.com/aleph-im/aleph-sdk-python/pull/236):
When deleting an instance, the behavior for the `ports-forwarding` aggregate is different between the CLI and the UI:
- The CLI will update the aggregate to keep the value of the item hash to the existing values (example: https://explorer.aleph.cloud/address/ETH/0x238224C744F4b90b4494516e074D2676ECfC6803/message/AGGREGATE/4acb1fac2b28a54c73160c1cdde93c51bb4712be10ca34f934b209b832b2ebbb). This may be an unwanted behavior to investigate, but it is not the scope of this tentative fix.
- The UI will update the aggregate to set the value of …

Fix: filter on crn list & port-forwarding 
